### PR TITLE
optparse-applicative >= 0.13.0.0 && < 0.14

### PR DESCRIPTION
**Pull request by srhb**
optparse-applicative is restricted to <0.8 which is very old and has stopped being distributed through for instance Nix, breaking webify entirely here. This PR bumps the dependency to >= 0.13 while preserving the behaviour of the options parser.

### CODE REVIEW

**Comment by srhb** [comment]
I don't think the Travis failure is really related to the upversioning of optparse-applicative at all. Compared to the previous build, it looks like a dependency broke in a minor version. Is this a blocker?

**Comment by ananthakumaran** [comment]
@srhb I don't have much bandwidth to maintain this project now. If you would like, I can provide you access to this repo and hackage.

**Comment by srhb** [comment]
Sounds good to me, though I will probably only be keeping it up to date with dependencies etc :)

**Comment by ananthakumaran** [comment]
@srhb added you as a collaborator. do you have a hackage account?

**Comment by srhb** [comment]
I do now, https://hackage.haskell.org/user/srhb

I'll take a look at fixing up things this weekend. Thanks for your quick responses.

**Comment by ananthakumaran** [comment]
added you on hackage as well

**Pull request merged**
